### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pombredanne** [tmm1/test-queue#20]
@tmm1 sry to be a bugger on this other repo of yours, but would you mind adding a license text and copyright for your MIT license?

**Comment by ryanong** [comment]
https://github.com/tmm1/test-queue/blob/master/test-queue.gemspec#L11

**Comment by bootstraponline** [comment]
[:+1:](https://github.com/tmm1/test-queue/blob/855e0f670f43e597ce87c5694fc34abe0792b3d2/test-queue.gemspec#L11)

http://choosealicense.com/licenses/mit/

**Comment by steshaw** [comment]
The licence does appear to be MIT

https://github.com/tmm1/test-queue/blob/master/test-queue.gemspec#L11

Just no LICENCE file.

**Comment by koic** [comment]
This issue has been resolved by #84.
