### ISSUE TITLE
Find order-dependent/random test case failure

### ISSUE THREAD

**Issue by astromahi** [tmm1/test-queue#93]
Hi,

How do we track down the order-dependent OR random test-case failure using test-queue framework. We have bunch of test suites collection which runs on our CI and powered by test-queue.

Is there any similar procedure explained in this?.
https://dev.to/pezza/using-minitest-s-seed-value-to-track-down-order-dependent-flaky-tests-119a

**Comment by koic** [comment]
In Minitest 0.6.0+, seed value could be specified with `SEED=1234 minitest-queue ...` or `minitest-queue --seed 1234 ...`. In other words, it conforms to Minitest:

- https://github.com/tmm1/test-queue/pull/108
- https://github.com/minitest/minitest
